// /api/customer/address/v1?CifId=AAJ5318
export const addressVerificationBody = [
    {
        "Id": 6,
        "CifId": "AAJ5318",
        "StreetAddr1": "97 Oak Ln",
        "StreetAddr2": "",
        "StreetAddr3": "",
        "City": "Richardson",
        "StateCode": "TX",
        "PostalCode": "75666",
        "NewStreetAddr1": "",
        "NewStreetAddr2": "",
        "NewStreetAddr3": "",
        "NewCity": "",
        "NewStateCode": "",
        "NewPostalCode": "",
        "StatusFlg": "VERIFIED",
        "Note": "Test addr POST",
        "CreatedBy": "vsharapo",
        "CreatedDt": "2018-11-12T11:16:33.013"
    },
    {
        "Id": 5,
        "CifId": "AAJ5318",
        "StreetAddr1": "97 Oak Ln",
        "StreetAddr2": "",
        "StreetAddr3": "",
        "City": "Richardson",
        "StateCode": "TX",
        "PostalCode": "75148",
        "NewStreetAddr1": "97 Oak Ln",
        "NewStreetAddr2": "",
        "NewStreetAddr3": "Richardson",
        "NewCity": "",
        "NewStateCode": "TX",
        "NewPostalCode": "75666",
        "StatusFlg": "MODIFY",
        "Note": "Test addr POST",
        "CreatedBy": "vsharapo",
        "CreatedDt": "2018-11-09T11:51:52.543"
    },
    {
        "Id": 4,
        "CifId": "AAJ5318",
        "StreetAddr1": "97 Oak Ln",
        "StreetAddr2": "",
        "StreetAddr3": "",
        "City": "Richardson",
        "StateCode": "TX",
        "PostalCode": "75148",
        "NewStreetAddr1": "97 Oak Ln",
        "NewStreetAddr2": "",
        "NewStreetAddr3": "Richardson",
        "NewCity": "",
        "NewStateCode": "TX",
        "NewPostalCode": "75666",
        "StatusFlg": "MODIFY",
        "Note": "Test addr POST",
        "CreatedBy": "vsharapo",
        "CreatedDt": "2018-11-09T11:24:05.883"
    },
    {
        "Id": 3,
        "CifId": "AAJ5318",
        "StreetAddr1": "97 Oak Ln",
        "StreetAddr2": "",
        "StreetAddr3": "",
        "City": "Richardson",
        "StateCode": "TX",
        "PostalCode": "75148",
        "NewStreetAddr1": "",
        "NewStreetAddr2": "",
        "NewStreetAddr3": "",
        "NewCity": "",
        "NewStateCode": "",
        "NewPostalCode": "",
        "StatusFlg": "VERIFIED",
        "Note": "Test addr POST",
        "CreatedBy": "vsharapo",
        "CreatedDt": "2018-11-09T11:20:53.963"
    }
];

// /api/customer/email/v1 POST
// POST: ADD
// {
// 	"CifId": "AAJ5318",
// 	"StreetAddr1": "97 Oak Ln",
// 	"StreetAddr2": "",
// 	"StreetAddr3": "",
// 	"City": "Richardson",
// 	"StateCode": "TX",
// 	"PostalCode": "75666",
// 	"NewStreetAddr1": "",
// 	"NewStreetAddr2": "",
// 	"NewStreetAddr3": "",
// 	"NewCity": "",
// 	"NewStateCode": "",
// 	"NewPostalCode": "",
// 	"Note": "Test addr POST",
// 	"StatusFlg": "VERIFIED",
// 	"CreatedBy": "vsharapo"
// }
