export let ciscocallNotitication = `<message from='pubsub.ibdc1-cce-fina01.ibkc.int' to='215194@ibdc1-cce-fina01.ibkc.int' id='/finesse/api/User/215194/Dialogs__215194@ibdc1-cce-fina01.ibkc.int__2K0nE'>
<event xmlns='http://jabber.org/protocol/pubsub#event'>
    <items node='/finesse/api/User/215194/Dialogs'>
        <item id='0b6afdb5-5870-4b69-b649-7e7a8c69c0c05638337'>
            <notification xmlns='http://jabber.org/protocol/pubsub'><Update><data><dialogs><Dialog><associatedDialogUri></associatedDialogUri><fromAddress>215194</fromAddress><id>19318761</id><mediaProperties><DNIS></DNIS><callType>OUT</callType><dialedNumber>14696014194</dialedNumber><outboundClassification></outboundClassification><callvariables><CallVariable><name>callVariable1</name><value></value></CallVariable><CallVariable><name>callVariable2</name><value></value></CallVariable><CallVariable><name>callVariable3</name><value></value></CallVariable><CallVariable><name>callVariable4</name><value></value></CallVariable><CallVariable><name>callVariable5</name><value></value></CallVariable><CallVariable><name>callVariable6</name><value></value></CallVariable><CallVariable><name>callVariable7</name><value></value></CallVariable><CallVariable><name>callVariable8</name><value></value></CallVariable><CallVariable><name>callVariable9</name><value></value></CallVariable><CallVariable><name>callVariable10</name><value></value></CallVariable></callvariables></mediaProperties><mediaType>Voice</mediaType><participants><Participant><actions></actions><mediaAddress>215194</mediaAddress><mediaAddressType>AGENT_DEVICE</mediaAddressType><startTime>2017-10-04T15:10:16.888Z</startTime><state>DROPPED</state><stateCause></stateCause><stateChangeTime>2017-10-04T15:10:55.206Z</stateChangeTime></Participant></participants><state>DROPPED</state><toAddress>14696014194</toAddress><uri>/finesse/api/Dialog/19318761</uri></Dialog></dialogs></data><event>DELETE</event><requestId></requestId><source>/finesse/api/User/215194/Dialogs</source></Update></notification>
        </item>
    </items>
</event>
</message>`;
