// /api/claccounts/v1?CampaignCd=DIRECT&CustomerName=John&StatusCd=CANCELED&AccountId=6900000669&CifId=MAG0694&PageNr=0&PageSize=5
export const claccountsBody =
  [
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076630,
      "AccountId": "6900551729",
      "AccountType": "D",
      "CifId": "WAA1486",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "589",
      "InterestDue": "5.32",
      "LastPaymentDt": "10/04/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/08/2017",
      "NextWorkDt": "12/09/2017",
      "OfficerName": "XTamica Campbell",
      "PastDueDays": "73",
      "CallPriority": 3,
      "StatusCd": "LOCKED",
      "LastCalledBy": "vsharapo",
      "LastCalledDt": "2017-12-20T04:40:10.95",
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "John S."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076629,
      "AccountId": "6900554178",
      "AccountType": "L",
      "CifId": "S309051",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "672",
      "InterestDue": ".91",
      "LastPaymentDt": "10/27/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/05/2017",
      "NextWorkDt": "12/06/2017",
      "OfficerName": "Leigh McMath",
      "PastDueDays": "20",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": '2017-01-01T01:30:11.95',
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Hayden C."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076628,
      "AccountId": "6900198695",
      "AccountType": "L",
      "CifId": "SAF5712",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "524",
      "InterestDue": "77.72",
      "LastPaymentDt": "10/27/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/05/2017",
      "NextWorkDt": "12/07/2017",
      "OfficerName": "Sonja L. Trahan Howard",
      "PastDueDays": "15",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Harrison F."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076627,
      "AccountId": "6900193811",
      "AccountType": "L",
      "CifId": "PAF1497",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "557",
      "InterestDue": "7.97",
      "LastPaymentDt": "11/17/2017",
      "LastPromiseDt": "12/05/2017",
      "LastWorkDt": "12/06/2017",
      "NextWorkDt": "12/07/2017",
      "OfficerName": "XMelanie Johnson",
      "PastDueDays": "18",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Edward C."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076626,
      "AccountId": "6900046001",
      "AccountType": "D",
      "CifId": "HAG1587",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "766",
      "InterestDue": "298.20",
      "LastPaymentDt": "08/14/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/08/2017",
      "NextWorkDt": "12/09/2017",
      "OfficerName": "Will Devening",
      "PastDueDays": "68",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Joe M."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076625,
      "AccountId": "6900483022",
      "AccountType": "L",
      "CifId": "TAK0188",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "619",
      "InterestDue": ".00",
      "LastPaymentDt": "11/24/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/06/2017",
      "NextWorkDt": "12/08/2017",
      "OfficerName": "Alice Screws",
      "PastDueDays": "13",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Keanu R."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076624,
      "AccountId": "6900399251",
      "AccountType": "D",
      "CifId": "WCB4013",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "578",
      "InterestDue": "63.44",
      "LastPaymentDt": "09/15/2017",
      "LastPromiseDt": "11/10/2017",
      "LastWorkDt": "12/08/2017",
      "NextWorkDt": "12/09/2017",
      "OfficerName": "Debbie Reynolds",
      "PastDueDays": "68",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Kate W."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076623,
      "AccountId": "6900528164",
      "AccountType": "L",
      "CifId": "HAD5291",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "423",
      "InterestDue": "53.91",
      "LastPaymentDt": "11/06/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/09/2017",
      "NextWorkDt": "12/10/2017",
      "OfficerName": "William Keedy",
      "PastDueDays": "32",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Leo C."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076622,
      "AccountId": "6900029585",
      "AccountType": "L",
      "CifId": "D049976",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "627",
      "InterestDue": "2.85",
      "LastPaymentDt": "11/06/2017",
      "LastPromiseDt": "12/04/2017",
      "LastWorkDt": "12/08/2017",
      "NextWorkDt": "12/09/2017",
      "OfficerName": "Shantel Hebert",
      "PastDueDays": "28",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Matthew M."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076621,
      "AccountId": "6900073021",
      "AccountType": "L",
      "CifId": "S306953",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "585",
      "InterestDue": "15.31",
      "LastPaymentDt": "11/22/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/07/2017",
      "NextWorkDt": "12/11/2017",
      "OfficerName": "Joann Speake",
      "PastDueDays": "18",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Sarah M."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076620,
      "AccountId": "6900087955",
      "AccountType": "L",
      "CifId": "PAD5095",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "478",
      "InterestDue": "209.55",
      "LastPaymentDt": "07/12/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/06/2017",
      "NextWorkDt": "12/09/2017",
      "OfficerName": "Juanita Johnson",
      "PastDueDays": "85",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Alyson H."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076619,
      "AccountId": "6900393817",
      "AccountType": "L",
      "CifId": "WAI1529",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "569",
      "InterestDue": "13.91",
      "LastPaymentDt": "11/16/2017",
      "LastPromiseDt": "12/08/2017",
      "LastWorkDt": "12/06/2017",
      "NextWorkDt": "12/11/2017",
      "OfficerName": "Teressa Anderson",
      "PastDueDays": "27",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "James M."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076618,
      "AccountId": "6900523470",
      "AccountType": "L",
      "CifId": "TAK0639",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "675",
      "InterestDue": ".00",
      "LastPaymentDt": "11/28/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/09/2017",
      "NextWorkDt": "12/11/2017",
      "OfficerName": "XChrista B. Posey",
      "PastDueDays": "11",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "David B."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076617,
      "AccountId": "6900140408",
      "AccountType": "L",
      "CifId": "FAE5385",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "726",
      "InterestDue": "59.81",
      "LastPaymentDt": "10/19/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/07/2017",
      "NextWorkDt": "12/08/2017",
      "OfficerName": "Emily Jensen",
      "PastDueDays": "42",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Michael F."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076616,
      "AccountId": "6900119782",
      "AccountType": "L",
      "CifId": "AAA1992",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "757",
      "InterestDue": "14.39",
      "LastPaymentDt": "10/20/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/06/2017",
      "NextWorkDt": "12/07/2017",
      "OfficerName": "Mary Gorman",
      "PastDueDays": "14",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Tom H."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076615,
      "AccountId": "6900233302",
      "AccountType": "L",
      "CifId": "TAE0943",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "652",
      "InterestDue": "210.81",
      "LastPaymentDt": "07/17/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/09/2017",
      "NextWorkDt": "12/11/2017",
      "OfficerName": "XSamuel Martinez",
      "PastDueDays": "23",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Robert D."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076614,
      "AccountId": "6900491694",
      "AccountType": "L",
      "CifId": "BAH3450",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "621",
      "InterestDue": "31.90",
      "LastPaymentDt": "10/19/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/08/2017",
      "NextWorkDt": "12/11/2017",
      "OfficerName": "Tracy Secrist",
      "PastDueDays": "20",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Scarlet J."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076613,
      "AccountId": "6900254043",
      "AccountType": "L",
      "CifId": "TAJ5531",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "523",
      "InterestDue": "7.25",
      "LastPaymentDt": "10/26/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "12/08/2017",
      "NextWorkDt": "12/11/2017",
      "OfficerName": "Leigh McMath",
      "PastDueDays": "23",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Mark R."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076612,
      "AccountId": "6903044631",
      "AccountType": "L",
      "CifId": "ACB6087",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": null,
      "InterestDue": "3.43",
      "LastPaymentDt": "10/18/2017",
      "LastPromiseDt": "12/07/2017",
      "LastWorkDt": "12/08/2017",
      "NextWorkDt": "12/09/2017",
      "OfficerName": "Ana Amaya",
      "PastDueDays": "20",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Jeff G."
    },
    {
      "CampaignCd": "DIRECT",
      "CampaignNm": "Direct",
      "CampaignRecordId": 1076611,
      "AccountId": "6900046126",
      "AccountType": "L",
      "CifId": "ZAD1242",
      "ColStatusCd": "P",
      "EaPcFlag": null,
      "FicoScore": "634",
      "InterestDue": "9.22",
      "LastPaymentDt": "11/03/2017",
      "LastPromiseDt": "00/00/0000",
      "LastWorkDt": "00/00/0000",
      "NextWorkDt": null,
      "OfficerName": "Shantel Hebert",
      "PastDueDays": "10",
      "CallPriority": 3,
      "StatusCd": "NEW",
      "LastCalledBy": null,
      "LastCalledDt": null,
      "NextCallDt": null,
      "NextCallUser": null,
      "CustomerName": "Samuel L."
    }
  ];
