export const collectorsProductivityBody = [
  {
    "UserCd": "ajaillet",
    "HoursWorked": "00:00",
    "OutboundCalls": 1,
    "AvgCallsPerHour": 2,
    "Contact": 3,
    "Promises": 4,
    "PaymentReceived": 5,
    "IncomingCalls": 6,
    "ContactPct": 7,
    "PromiseToContactPct": 8,
    "TotalCalls": 9
  },
  {
    "UserCd": "clandry",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 3,
    "Contact": 5,
    "Promises": 6,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 10,
    "PromiseToContactPct": 9 ,
    "TotalCalls": 0
  },
  {
    "UserCd": "dprosper",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 0,
    "Contact": 12,
    "Promises": 8,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 15,
    "PromiseToContactPct": 12,
    "TotalCalls": 0
  },
  {
    "UserCd": "jamjones",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 10,
    "Contact": 0,
    "Promises": 0,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 0,
    "PromiseToContactPct": 0,
    "TotalCalls": 0
  },
  {
    "UserCd": "jsteel",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 3,
    "Contact": 0,
    "Promises": 0,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 0,
    "PromiseToContactPct": 0,
    "TotalCalls": 0
  },
  {
    "UserCd": "mmuratti",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 15,
    "Contact": 0,
    "Promises": 0,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 0,
    "PromiseToContactPct": 0,
    "TotalCalls": 0
  },
  {
    "UserCd": "nkilchr",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 5,
    "Contact": 0,
    "Promises": 0,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 0,
    "PromiseToContactPct": 0,
    "TotalCalls": 0
  },
  {
    "UserCd": "nkilchri",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 3,
    "Contact": 0,
    "Promises": 0,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 0,
    "PromiseToContactPct": 0,
    "TotalCalls": 0
  },
  {
    "UserCd": "pblanco",
    "OutboundCalls": 0,
    "AvgCallsPerHour": 8,
    "Contact": 0,
    "Promises": 0,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 0,
    "PromiseToContactPct": 0,
    "TotalCalls": 0
  },
  {
    "UserCd": "vsharapo",
    "OutboundCalls": 2,
    "HoursWorked": "08:30",
    "AvgCallsPerHour": 15,
    "Contact": 0,
    "Promises": 0,
    "PaymentReceived": 0,
    "IncomingCalls": 0,
    "ContactPct": 0,
    "PromiseToContactPct": 0,
    "TotalCalls": 0
  }
];
